version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=messages
      - POSTGRES_PASSWORD=messages
      - POSTGRES_DB=messages
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: